### ISSUE TITLE
Implement `Conjecture 2.1` cost function and implement common features in `opt` or `graph` crate

### ISSUE THREAD

**Issue by ariasanovsky** [ariasanovsky/azdopt#21]
There's still a lot of hard-coding in `examples/05-ah.rs`.
To remedy this, let's work on `Conjecture 2.1` and make it easier to visualize the exploration.

- [x] Implement `Conjecture 2.1` cost function with (horribly slow) method for matching number.
- [x] More detailed logging
  - [x] use a `ShortForm` trait to compress graphs in `g6` form
    - Derive `ShortForm` for `SearchNode<S>` from `S` (with `time`?)
  - [x] Allow cost functions to return non-`f32` data:
    - E.g., `AH` conjecture cost function uses $\text{diam}, k, \partial_k, \pi$
      - This value can produce a `f32` from $\pi + \partial_k$
    - By default, the cost function returns a `f32`
    - E.g., `Conjecture 2.1` will have $\lambda_1$ and $\mu$
  - [x] Upgrade `plot_graphs.py` to support more 
- [x] ~~Suppose larger values of `N`~~ moved to Issue #22 
  - ~~Implement a `B64` and `B128` for larger values of `N`~~
    - ~~This will be required for Issuee [#15](https://github.com/ariasanovsky/azdopt/issues/15)~~
- [x] Use random values of `time` and `p` (random edge density) for tree roots
  - We could support `usize` and `usize` ranges
- [x] ~~Support stagnation detection~~ Task moved to #14 
  - This resolves Issue [#17](https://github.com/ariasanovsky/azdopt/issues/17)
- [x] Move the data-parallel methods from `examples/05-ah.rs` to their home
  - This may require making/using a `Generate` method
    - E.g., sample `p`, and the random graph
    - Also derive the `Generate` from `S` onto `StateNode<S>`
- [x] Check if Issue [#16](https://github.com/ariasanovsky/azdopt/issues/16) is obsolete
- [x] ~~Account for `ActionsTaken` when planning for non-commutative action spaces~~ moved to 
  - We are allowed to identify graphs visited from the root by the (unordered) set of changes
  - However, other spaces need not satisfy this law
  - [x] This will become its own issue most likely
- [x]  ~~Make an Issue for state stacks and CNNs~~ moved to #14 
- [x] ~~Make an Issue to refactor `IQMinTree` and `examples/04-r44.rs` to match `INTMinTree`~~
  - moved to #14 instead
- [x] Make an Issue to bring back the `BlockTree`
  - Useful for finding all cut-edges quickly
  - Better to track than recompute when `N` is large
  - Can eventually improve computation of distances and distance matrix
  - Possibly useful for maximum matches?
  - Return to the typestate approach?
  - `BitsetGraphRef`?
